### ISSUE TITLE
on failure.

### ISSUE THREAD

**Issue by luca-ing** [devchattv/freelancerstopics#1]
An episode on failing in your freelancing endeavours.
This could mean just failure of a particular facet of your business, or outright failing as a freelancer, and having to crawl back to The Man and regular employment to feed your family.

Maybe consider the effects of failure:
* What does it mean to fail - for your psyche, your family, your position in your community?
* How does it feel?
* How do others react to learning of this about you?
* How can you pick yourself back up - and possibly turn it into a lesson that benefits you in the long run?

But, more importantly:
* Were there warning signs?
* Could you have averted failure?
* Once you've spotted warning signs, how can you change course (especially in light of the fact that you are probably short on cash and hustling flat-out already by this point)?
* How do you know that you are indeed about to fail, and not just in a lull / have to wait a little longer until a new approach finally picks up?
* Any other lessons learned?

**Comment by cmaxw** [comment]
Recorded 03/15/2016
