### ISSUE TITLE
on remote consulting.

### ISSUE THREAD

**Issue by luca-ing** [devchattv/freelancerstopics#2]
An episode on purely remote consulting. Perhaps never meeting the customer face to face.

Communication technologies:
* for meetings (e.g. chat, video conferencing)
* for project management
* for day-to-day communication
* which software tools can you expect customers to be familiar with / have installed (e.g. Skype)

Communication techniques:
* how to manage your clients' expectations and discussion style
* how to lead discussions
* how to share impromptu drawings / sketches (as you would create on a whiteboard)
* how to make up for a lack of non-verbal communication
* common miscommunication pitfalls to spot or avoid in the first place
* How to deal with time zone differences?

Fundamentals:
What about if what you're selling is not a tangible product (say, a piece of software), but plain communication (e.g. strategy consulting)? Does that work? How? How do customers react if you suggest purely remote consulting? Can I as a random consultant really expect it to be sustainable, or does it merely work for a lucky few consultants who are just so good (or well-known) that customers will accept this as a term of working together?

**Comment by cmaxw** [comment]
Recorded 7/12/16
