### ISSUE TITLE
On starting out cold.

### ISSUE THREAD

**Issue by luca-ing** [devchattv/freelancerstopics#3]
An episode on how to start as a freelancer without already having standing in your chosen niche.

Allow me to take myself as an example:
I am an engineer who has worked as an employed consultant (thus not freelance) in many different companies, in many different roles (specification, development, testing). However now I would like to offer consulting services which focus on improving quality through better processes and tool use (be that during SW design, implementation or testing).
I *know* I have good knowledge of these topics, and having worked with many clients I know there is a real need for what I want to offer.
However, I've never officially worked on process issues, so I am not recognised in this field, have no reputation or references, and much fewer contacts that if I had been freelancer for a while and just wanted to enter a different field.
Let's ignore the legalities around this, like taxes, perhaps founding a company etc.
Instead, let's concentrate on the very foundation: how do I find my first clients?

Problems:
* I have no references.
* I am utterly unknown.
* I certainly have no following, neither on Twitter, nor a blog or something.
* Not having had any clients, I'm not able to cite past experience
* I don't have money or time to spare for experiments, so whatever marketing approaches I attempt have to have at least a good probability of  success unless they are cheap and quick (yeah right)

Questions:
* How do I even get noticed? I've started a blog, but not even my mom reads it at this point :-)
* How can I convince a client to try me out even though I'm apparently an total n00b in this field?
* I face some competition in my chosen field (but I think my focus is narrow enough, and the market huge enough that it isn't really a problem) - how do I deal with the fact that there is more experienced competition? Is there even a way to turn this situation into an advantage for me?
* How can I distinguish impostor syndrome from actual gaps in my knowledge / experience?

**Comment by cmaxw** [comment]
Recorded 01/12/2016

**Comment by cmaxw** [comment]
Released 02/04/2016
